apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
data:
  # Note: These are example base64 encoded values. In production, use proper secrets management
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres
  JWT_SECRET: eW91ci1zZWNyZXQta2V5  # your-secret-key
  AWS_ACCESS_KEY_ID: eW91ci1hY2Nlc3Mta2V5  # your-access-key
  AWS_SECRET_ACCESS_KEY: eW91ci1zZWNyZXQta2V5  # your-secret-key 